---
title: "hw6"
author: "Ran Wang"
date: "11/21/2019"
output: git_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1)
library(tidyverse)
library(viridis)
library(ggridges)
library(patchwork)
library(tidyverse)
library(rvest)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

```{r probelm1}
birthweight = read.csv("./datahw6/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(babysex= as.factor(babysex),
         babysex= recode(babysex,"1"="male","2"="female"),
         frace = as.factor(frace),
         frace = recode(frace,"1" = "White", "2" = "Black", "3" = "Asian", "4" = "Puerto Rican", "8" = "Other", "9" = "Unknown"),
         mrace = as.factor(mrace),
         mrace = recode(mrace,"1" = "White", "2" = "Black", "3" = "Asian", "4" = "Puerto Rican", "8" = "Other", "9" = "Unknown"),
         malform = as.factor(malform),
         malform = recode(malform,"0" = "absent", "1" = "present")
         )

```


```{r probelm1_backwise}
fullmodel <- lm(bwt ~ ., data = birthweight) 
summary(fullmodel)

step(fullmodel,direction = "backward") 

#final model
linear_model = lm(bwt ~ babysex + bhead + blength + delwt + fincome + 
    gaweeks + mheight + mrace + parity + ppwt + smoken, data = birthweight) 

summary(linear_model)

#calculate the residual and predicted value
residual = modelr::add_residuals(birthweight, linear_model)
prediction = modelr::add_predictions(birthweight, linear_model)

residual_prediction = full_join(residual,prediction)

plot1 = residual_prediction %>% 
   ggplot(aes(x = pred, y = resid,color = blength)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Residual vs. Prediction",
    x = "Predicted Value",
    y = "Residual") +
  geom_hline(aes(yintercept = 0), color = "black")
  
plot1


cv_df =
  crossv_mc(birthweight, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_df = 
  cv_df %>% 
  mutate(linear_model  = map(train, ~lm(bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = .x)),
         model_1  = map(train,~lm(bwt ~ blength + gaweeks, data = .x)),
         model_2  = map(train, ~lm(bwt ~ bhead * blength + bhead * babysex + babysex * blength + bhead * babysex * blength, data = .x))) %>%
  mutate(rmse_linear = map2_dbl(linear_model, test, ~rmse(model = .x, data = .y)),
         rmse_model_1 = map2_dbl(model_1, test, ~rmse(model = .x, data = .y)),
         rmse_model_2 = map2_dbl(model_2, test, ~rmse(model = .x, data = .y))
         )
  
cv_df  



plot2 = cv_df  %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse, fill = model)) +
  geom_violin(trim = FALSE, alpha = 0.5) +
  geom_jitter(shape = 16, position = position_jitter(0.2), alpha = 0.15) 
plot2
```

## Probelm 2

```{r p2_r2}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())


bootstrap_sample = weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
        models = map(strap, ~lm(tmax ~ tmin, data = .x)),
        results = map(models, broom::tidy),
        var = map(models, broom::glance)
        ) %>% 
  select(-strap, -models) %>% 
  unnest(results,var)

plot_r_squared = bootstrap_sample %>% 
  filter(term == "tmin") %>% 
  ggplot(aes(x = r.squared)) + 
  geom_density() +
  labs(
    title = "Density Plot of R squared",
    x = "R squared",
    y = "Density") +
  geom_vline(aes(xintercept = mean(r_squared)))

plot_r_squared 


ci_r_squared = bootstrap_sample %>% 
  filter(term == "tmin") %>% 
  pull(var = r.squared) %>% 
  quantile(c(0.025, 0.975))
```

```{r p2_log}
bootstrap_sample2 = bootstrap_sample %>% 
  select(.id, term, estimate) %>% 
  pivot_wider(
    id_cols = .id,
    names_from = term,
    values_from = estimate
  ) %>% 
  janitor::clean_names() %>% 
  mutate(log = log(intercept * tmin))

plot_log = bootstrap_sample2 %>% 
  ggplot(aes(x = log)) + 
  geom_density() +
  labs(
    title = "Density Plot of log(beta0_hat * beta1_hat)",
    x = "log(beta0_hat * beta1_hat)",
    y = "Density") +
   geom_vline(aes(xintercept = mean(log)))
plot_log

ci_log = bootstrap_sample2 %>% 
  pull(log) %>% 
  quantile(c(0.025, 0.975))

ci_log 
```

